# Minecraft: Story Mode - Purple Sunset Skybox (dusk)
source=./sky_sunset.png
startFadeIn=17:00
endFadeIn=18:00
startFadeOut=19:30
endFadeOut=20:30
blend=alpha
rotate=false
speed=0.0
axis=0.0 1.0 0.0
