package net.mcsm.extras.client;

import com.mojang.blaze3d.vertex.PoseStack.Pose;
import com.mojang.blaze3d.vertex.VertexConsumer;

import net.dabicco.witherstormmod.client.ClientDistantStormManager;
import net.dabicco.witherstormmod.config.DabyWSClientConfig;
import net.fabricmc.fabric.api.client.rendering.v1.level.LevelRenderContext;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.SubmitNodeCollector;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.resources.Identifier;
import net.minecraft.util.Mth;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.Vec3;

/**
 * Devouring Storms 1.9.201 — the extracted OG skies finally RENDER.
 *
 * The mcsm_atmosphere/sky strips are vertical zenith-&gt;horizon gradients that
 * 1.9.199/1.9.200 shipped as dead assets: nothing ever drew them, which is
 * exactly the "the skies are not rendering" report.  McsmGlarePalettes carries
 * those strips as 16-stop ramps (generated by ci/make_glare_from_sky.py) and
 * this dome paints them onto a camera-centred sky shell: calm day/sunset/night
 * decks by clock time, blended toward the phase decks while a storm is near.
 *
 * The dome is translucent (alpha &lt; 255) so the vanilla sun/moon/stars and the
 * cloud decks still read through it; terrain closer than the shell occludes it
 * for free, matching the reference frames where roofs/trees cut the gradient.
 */
public final class McsmSkyDome {

    private static final Identifier WHITE = Identifier.fromNamespaceAndPath(
            "dabywitherstormmod", "textures/misc/storm_white.png");

    /** shell radius in blocks; terrain inside this still cuts the gradient. */
    private static final double SHELL = 430.0D; // inside the far plane even at 8 chunks (4*128=512)

    private static final int SECTORS = 16;   // azimuth segments
    private static final int BANDS = 9;      // elevation rings: -18deg .. +90deg

    private McsmSkyDome() {
    }

    private static float smooth(float t) {
        t = Mth.clamp(t, 0.0F, 1.0F);
        return t * t * (3.0F - 2.0F * t);
    }

    /** calm deck mix for the time of day, written into out[3]. */
    private static void calmRamp(long time, float[] out) {
        float t = (float) (time % 24000L);
        float wDay = smooth((t - 23000.0F) / 2000.0F) * (1.0F - smooth((t - 11500.0F) / 1500.0F));
        float wSunset = smooth((t - 11500.0F) / 1200.0F) * (1.0F - smooth((t - 13300.0F) / 1200.0F));
        float wNight = smooth((t - 13000.0F) / 1500.0F) * (1.0F - smooth((t - 22700.0F) / 1800.0F));
        float tot = Math.max(0.001F, wDay + wSunset + wNight);
        mix(McsmGlarePalettes.DAY, McsmGlarePalettes.SUNSET, McsmGlarePalettes.NIGHT,
                wDay / tot, wSunset / tot, wNight / tot, out);
    }

    /** storm deck for a phase; returns 0 when calm owns the sky. */
    private static float stormRamp(float phase, float[] out) {
        float[][] deck;
        float w;
        if (phase >= 5.9F) {
            deck = McsmGlarePalettes.P6;
            w = smooth((phase - 5.9F) / 0.3F);
        } else if (phase >= 5.48F) {
            deck = McsmGlarePalettes.P55;
            w = smooth((phase - 5.48F) / 0.2F) * (1.0F - smooth((phase - 5.9F) / 0.2F));
        } else if (phase >= 5.25F) {
            deck = McsmGlarePalettes.P5_PURPLE;
            w = smooth((phase - 5.25F) / 0.2F) * (1.0F - smooth((phase - 5.48F) / 0.2F));
        } else if (phase >= 4.9F) {
            deck = McsmGlarePalettes.P5_TEAL;
            w = smooth((phase - 4.9F) / 0.2F) * (1.0F - smooth((phase - 5.25F) / 0.2F));
        } else if (phase >= 3.9F) {
            deck = McsmGlarePalettes.P4;
            w = smooth((phase - 3.9F) / 0.4F) * (1.0F - smooth((phase - 4.9F) / 0.3F));
        } else {
            return 0.0F;
        }
        for (int i = 0; i < McsmGlarePalettes.STOPS; i++) {
            out[i * 3] = deck[i][0];
            out[i * 3 + 1] = deck[i][1];
            out[i * 3 + 2] = deck[i][2];
        }
        return w;
    }

    private static void mix(float[][] a, float[][] b, float[][] c,
                            float wa, float wb, float wc, float[] out) {
        for (int i = 0; i < McsmGlarePalettes.STOPS; i++) {
            out[i * 3] = a[i][0] * wa + b[i][0] * wb + c[i][0] * wc;
            out[i * 3 + 1] = a[i][1] * wa + b[i][1] * wb + c[i][1] * wc;
            out[i * 3 + 2] = a[i][2] * wa + b[i][2] * wb + c[i][2] * wc;
        }
    }

    private static void rampAt(float[] ramp, float pos, float[] out) {
        float f = Mth.clamp(pos, 0.0F, 1.0F) * (McsmGlarePalettes.STOPS - 1);
        int i = (int) f;
        float fr = f - i;
        if (i >= McsmGlarePalettes.STOPS - 1) {
            out[0] = ramp[(McsmGlarePalettes.STOPS - 1) * 3];
            out[1] = ramp[(McsmGlarePalettes.STOPS - 1) * 3 + 1];
            out[2] = ramp[(McsmGlarePalettes.STOPS - 1) * 3 + 2];
            return;
        }
        out[0] = ramp[i * 3] + (ramp[(i + 1) * 3] - ramp[i * 3]) * fr;
        out[1] = ramp[i * 3 + 1] + (ramp[(i + 1) * 3 + 1] - ramp[i * 3 + 1]) * fr;
        out[2] = ramp[i * 3 + 2] + (ramp[(i + 1) * 3 + 2] - ramp[i * 3 + 2]) * fr;
    }

    public static void submit(LevelRenderContext ctx) {
        Minecraft mc = Minecraft.getInstance();
        if (mc == null || mc.level == null || mc.player == null) {
            return;
        }
        if (mc.level.dimension() != Level.OVERWORLD) {
            return;
        }
        // 1.9.202: the calm decks also ride the customSkyboxes gate (forced on
        // by the MCSM client gate), so the skies render even when a stale
        // config left storyModeSky off.
        boolean calmOn = DabyWSClientConfig.storyModeSky || DabyWSClientConfig.customSkyboxes;
        float phase = 0.0F;
        double bestD = Double.MAX_VALUE;
        for (ClientDistantStormManager.StormData d : ClientDistantStormManager.all()) {
            if (d.phase > phase) {
                phase = d.phase;
            }
            if (d.phase >= 3.9F) {
                double dx = d.dispX - mc.player.getX();
                double dy = d.dispY - mc.player.getY();
                double dz = d.dispZ - mc.player.getZ();
                bestD = Math.min(bestD, dx * dx + dy * dy + dz * dz);
            }
        }
        float stormW = 0.0F;
        if (phase >= 3.9F && bestD < 1700.0D * 1700.0D) {
            stormW = smooth((phase - 3.9F) / 0.6F)
                    * (1.0F - Mth.clamp((float) ((Math.sqrt(bestD) - 900.0D) / 800.0D), 0.0F, 1.0F));
        }
        if (!calmOn && stormW <= 0.01F) {
            return;
        }

        float[] calm = new float[McsmGlarePalettes.STOPS * 3];
        calmRamp(mc.level.getGameTime() + (long) (mc.getDeltaTracker().getGameTimeDeltaPartialTick(false) * 50.0F), calm);
        float[] storm = new float[McsmGlarePalettes.STOPS * 3];
        float stormDeck = stormW > 0.01F ? stormRamp(phase, storm) : 0.0F;
        // 1.9.202: commit hard to the phase decks once a storm is near. The old
        // 0.85 cap let vanilla's pink/orange sunset bleed through and wash out
        // the teal vault the user wants (09-10 screenshots vs the 09-06 target).
        float blend = Mth.clamp(stormW, 0.0F, 1.0F)
                * Mth.clamp(0.40F + stormDeck, 0.0F, 1.0F) * 0.96F;

        final float[] ramp = new float[McsmGlarePalettes.STOPS * 3];
        for (int i = 0; i < ramp.length; i++) {
            ramp[i] = calm[i] + (storm[i] - calm[i]) * blend;
        }
        // 1.9.202: much less see-through — 175..235 so the vanilla sunset can no
        // longer tint the dome; the sun/moon/stars still show around it.
        final int alpha = (int) (175.0F + 60.0F * blend);

        Vec3 cam = ctx.levelState().cameraRenderState.pos;
        SubmitNodeCollector collector = ctx.submitNodeCollector();
        collector.submitCustomGeometry(ctx.poseStack(), RenderTypes.entityTranslucentEmissive(WHITE),
                (pose, consumer) -> {
                    // elevation bands from -18deg (below horizon, fog seam)
                    // to +90; per-vertex colour sampled from the blended ramp.
                    float[] c0 = new float[3];
                    float[] c1 = new float[3];
                    for (int b = 0; b < BANDS; b++) {
                        double e0 = -18.0D + (108.0D * b / BANDS);
                        double e1 = -18.0D + (108.0D * (b + 1) / BANDS);
                        // elevation -> ramp position: 90deg=0(zenith) 0deg=1(horizon)
                        float p0 = (float) ((90.0D - e1) / 90.0D);
                        float p1 = (float) ((90.0D - e0) / 90.0D);
                        p0 = Mth.clamp(p0, 0.0F, 1.0F);
                        p1 = Mth.clamp(p1, 0.0F, 1.0F);
                        for (int s = 0; s < SECTORS; s++) {
                            double a0 = Math.toRadians(360.0D * s / SECTORS);
                            double a1 = Math.toRadians(360.0D * (s + 1) / SECTORS);
                            rampAt(ramp, p0, c0);
                            rampAt(ramp, p1, c1);
                            Vec3 v00 = dir(e0, a0), v10 = dir(e0, a1);
                            Vec3 v01 = dir(e1, a0), v11 = dir(e1, a1);
                            vtx(pose, consumer, cam.add(v00.scale(SHELL)), c1, alpha);
                            vtx(pose, consumer, cam.add(v10.scale(SHELL)), c1, alpha);
                            vtx(pose, consumer, cam.add(v11.scale(SHELL)), c0, alpha);
                            vtx(pose, consumer, cam.add(v01.scale(SHELL)), c0, alpha);
                        }
                    }
                });
    }

    private static Vec3 dir(double elevDeg, double azim) {
        double ce = Math.cos(Math.toRadians(elevDeg));
        return new Vec3(Math.cos(azim) * ce, Math.sin(Math.toRadians(elevDeg)), Math.sin(azim) * ce);
    }

    private static void vtx(Pose pose, VertexConsumer consumer, Vec3 at, float[] rgb, int a) {
        consumer.addVertex(pose, (float) at.x, (float) at.y, (float) at.z)
                .setColor((int) (rgb[0] * 255.0F), (int) (rgb[1] * 255.0F), (int) (rgb[2] * 255.0F), a)
                .setUv(0.5F, 0.5F)
                .setOverlay(OverlayTexture.NO_OVERLAY)
                .setLight(15728880)
                .setNormal(pose, 0.0F, 1.0F, 0.0F);
    }
}
