package net.mcsm.extras.client;

import com.mojang.blaze3d.vertex.PoseStack.Pose;
import com.mojang.blaze3d.vertex.VertexConsumer;

import net.dabicco.witherstormmod.client.ClientDistantStormManager;
import net.dabicco.witherstormmod.config.DabyWSClientConfig;
import net.fabricmc.fabric.api.client.rendering.v1.level.LevelRenderContext;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.SubmitNodeCollector;
import net.minecraft.client.renderer.rendertype.RenderTypes;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.resources.Identifier;
import net.minecraft.util.Mth;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.Vec3;

/**
 * Devouring Storms 1.9.201 — the extracted OG skies finally RENDER.
 *
 * The mcsm_atmosphere/sky strips are vertical zenith-&gt;horizon gradients that
 * 1.9.199/1.9.200 shipped as dead assets: nothing ever drew them, which is
 * exactly the "the skies are not rendering" report.  McsmGlarePalettes carries
 * those strips as 16-stop ramps (generated by ci/make_glare_from_sky.py) and
 * this dome paints them onto a camera-centred sky shell: calm day/sunset/night
 * decks by clock time, blended toward the phase decks while a storm is near.
 *
 * The dome is translucent (alpha &lt; 255) so the vanilla sun/moon/stars and the
 * cloud decks still read through it; terrain closer than the shell occludes it
 * for free, matching the reference frames where roofs/trees cut the gradient.
 */
public final class McsmSkyDome {

    private static final Identifier WHITE = Identifier.fromNamespaceAndPath(
            "dabywitherstormmod", "textures/misc/storm_white.png");

    /** shell radius in blocks; terrain inside this still cuts the gradient. */
    private static final double SHELL = 430.0D; // inside the far plane even at 8 chunks (4*128=512)

    private static final int SECTORS = 16;   // azimuth segments
    private static final int BANDS = 9;      // elevation rings: -18deg .. +90deg

    private McsmSkyDome() {
    }

    /** 1.9.212: horizon colour of the calm deck -- the vanilla twilight fog
     *  is pink/purple and it washed the night horizon below the dome, so the
     *  frame fog colour is re-matched to this deck instead. */
    public static void calmHorizon(long time, float[] out) {
        float[] ramp = new float[McsmGlarePalettes.STOPS * 3];
        calmRamp(time, ramp);
        int last = (McsmGlarePalettes.STOPS - 1) * 3;
        out[0] = ramp[last];
        out[1] = ramp[last + 1];
        out[2] = ramp[last + 2];
    }

    private static float smooth(float t) {
        t = Mth.clamp(t, 0.0F, 1.0F);
        return t * t * (3.0F - 2.0F * t);
    }

    /** calm deck mix for the time of day, written into out[3].
     *  1.9.208: night splits into NIGHT and deep MIDNIGHT (user's midnight
     *  skybox) around 18000 ticks. */
    private static void calmRamp(long time, float[] out) {
        float t = (float) (time % 24000L);
        float wDay = smooth((t - 23000.0F) / 2000.0F) * (1.0F - smooth((t - 11500.0F) / 1500.0F));
        float wSunset = smooth((t - 11500.0F) / 1200.0F) * (1.0F - smooth((t - 13300.0F) / 1200.0F));
        float wNight = smooth((t - 13000.0F) / 1500.0F) * (1.0F - smooth((t - 22700.0F) / 1800.0F));
        float wMidnight = smooth((t - 17500.0F) / 1500.0F) * (1.0F - smooth((t - 22700.0F) / 1800.0F));
        float tot = Math.max(0.001F, wDay + wSunset + wNight);
        // build NIGHT base then blend down toward MIDNIGHT
        mix(McsmGlarePalettes.DAY, McsmGlarePalettes.SUNSET, McsmGlarePalettes.NIGHT,
                wDay / tot, wSunset / tot, wNight / tot, out);
        float wm = Math.min(1.0F, wMidnight);
        for (int i = 0; i < McsmGlarePalettes.STOPS; i++) {
            out[i * 3]     += (McsmGlarePalettes.MIDNIGHT[i][0] - out[i * 3]) * wm;
            out[i * 3 + 1] += (McsmGlarePalettes.MIDNIGHT[i][1] - out[i * 3 + 1]) * wm;
            out[i * 3 + 2] += (McsmGlarePalettes.MIDNIGHT[i][2] - out[i * 3 + 2]) * wm;
        }
    }

    /** storm deck for a phase; returns 0 when calm owns the sky. */
    private static float stormRamp(float phase, float[] out) {
        float[][] deck;
        float w;
        if (phase >= 8.0F) {
            // 1.9.208: phase 8-9 -- the whole sky burns dark-orange/ember.
            deck = McsmGlarePalettes.P89;
            w = smooth((phase - 8.0F) / 0.5F);
        } else if (phase >= 7.0F) {
            deck = McsmGlarePalettes.P6;
            w = 1.0F; // held until phase 8 hands over to P89
        } else if (phase >= 5.9F) {
            deck = McsmGlarePalettes.P6;
            w = smooth((phase - 5.9F) / 0.3F);
        } else if (phase >= 5.48F) {
            deck = McsmGlarePalettes.P55;
            w = smooth((phase - 5.48F) / 0.2F) * (1.0F - smooth((phase - 5.9F) / 0.2F));
        } else if (phase >= 5.25F) {
            deck = McsmGlarePalettes.P5_PURPLE;
            w = smooth((phase - 5.25F) / 0.2F) * (1.0F - smooth((phase - 5.48F) / 0.2F));
        } else if (phase >= 4.9F) {
            deck = McsmGlarePalettes.P5_TEAL;
            w = smooth((phase - 4.9F) / 0.2F) * (1.0F - smooth((phase - 5.25F) / 0.2F));
        } else if (phase >= 3.9F) {
            deck = McsmGlarePalettes.P4;
            w = smooth((phase - 3.9F) / 0.4F) * (1.0F - smooth((phase - 4.9F) / 0.3F));
        } else {
            return 0.0F;
        }
        for (int i = 0; i < McsmGlarePalettes.STOPS; i++) {
            out[i * 3] = deck[i][0];
            out[i * 3 + 1] = deck[i][1];
            out[i * 3 + 2] = deck[i][2];
        }
        return w;
    }

    private static void mix(float[][] a, float[][] b, float[][] c,
                            float wa, float wb, float wc, float[] out) {
        for (int i = 0; i < McsmGlarePalettes.STOPS; i++) {
            out[i * 3] = a[i][0] * wa + b[i][0] * wb + c[i][0] * wc;
            out[i * 3 + 1] = a[i][1] * wa + b[i][1] * wb + c[i][1] * wc;
            out[i * 3 + 2] = a[i][2] * wa + b[i][2] * wb + c[i][2] * wc;
        }
    }

    private static void rampAt(float[] ramp, float pos, float[] out) {
        float f = Mth.clamp(pos, 0.0F, 1.0F) * (McsmGlarePalettes.STOPS - 1);
        int i = (int) f;
        float fr = f - i;
        if (i >= McsmGlarePalettes.STOPS - 1) {
            out[0] = ramp[(McsmGlarePalettes.STOPS - 1) * 3];
            out[1] = ramp[(McsmGlarePalettes.STOPS - 1) * 3 + 1];
            out[2] = ramp[(McsmGlarePalettes.STOPS - 1) * 3 + 2];
            return;
        }
        out[0] = ramp[i * 3] + (ramp[(i + 1) * 3] - ramp[i * 3]) * fr;
        out[1] = ramp[i * 3 + 1] + (ramp[(i + 1) * 3 + 1] - ramp[i * 3 + 1]) * fr;
        out[2] = ramp[i * 3 + 2] + (ramp[(i + 1) * 3 + 2] - ramp[i * 3 + 2]) * fr;
    }

    /** 1.9.213: the sky shell is DELETED -- it read as a weird dome under
     *  the shader. The MCSM Visual Shader (or the base mod's Story Mode sky
     *  tint) owns the sky now; this class only keeps the deck ramps for the
     *  fog colour matching. */
    public static void submit(LevelRenderContext ctx) {
    }

    private static Vec3 dir(double elevDeg, double azim) {
        double ce = Math.cos(Math.toRadians(elevDeg));
        return new Vec3(Math.cos(azim) * ce, Math.sin(Math.toRadians(elevDeg)), Math.sin(azim) * ce);
    }

    private static void vtx(Pose pose, VertexConsumer consumer, Vec3 at, float[] rgb, int a) {
        consumer.addVertex(pose, (float) at.x, (float) at.y, (float) at.z)
                .setColor((int) (rgb[0] * 255.0F), (int) (rgb[1] * 255.0F), (int) (rgb[2] * 255.0F), a)
                .setUv(0.5F, 0.5F)
                .setOverlay(OverlayTexture.NO_OVERLAY)
                .setLight(15728880)
                .setNormal(pose, 0.0F, 1.0F, 0.0F);
    }
}
