#!/usr/bin/env python3
"""make_glare_from_sky.py — glare + sky palettes EXTRACTED from the OG strips.

The 1.9.200 feedback batch: the glare reads as a single flat colour and the
extracted sky gradients (mcsm_atmosphere/sky/*.png) never render.  The glare
PNGs that shipped were 100% transparent, so this generator rebuilds the whole
atmosphere straight out of the extracted reference strips:

  * samples each 1024x1024 sky gradient as a 16-stop zenith->horizon ramp;
  * writes real multi-colour radial glare discs (mcsm_atmosphere/glare/*.png)
    whose centre is the bright horizon band, mid the saturated middle stops
    and rim the dark zenith, with the hot-pink horizon ring re-added for the
    5.5/5.9/6 decks;
  * repairs the broken jar-overrides sky/phase4.png (was half black / half
    flat blue) with a proper icy-blue gradient and mirrors it into src;
  * emits McsmGlarePalettes.java carrying every ramp as float arrays so the
    runtime sky dome and glare use the exact extracted colours without any
    PNG decoding on the client.

Usage: python3 ci/make_glare_from_sky.py
Writes into BOTH src/main/resources/... and jar-overrides/... plus the Java
palette header.  Read-only analysis: python3 ci/make_glare_from_sky.py --check
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from pngutil import read_png, write_png, scale  # noqa: E402

SRC = "src/main/resources/assets/dabywitherstormmod/textures"
OVR = "jar-overrides/assets/dabywitherstormmod/textures"

STOPS = 16  # zenith -> horizon samples per deck


def ramp_from(path, n=STOPS):
    w, h, px = read_png(path)
    out = []
    for i in range(n):
        y = min(h - 1, round(i * (h - 1) / (n - 1)))
        r, g, b, a = px[y * w + w // 2]
        out.append((r, g, b))
    return out


def lerp(a, b, t):
    return tuple(a[i] + (b[i] - a[i]) * t for i in range(3))


def sample_ramp(ramp, pos):
    """pos in 0(top)..1(bottom); linear between stops."""
    pos = max(0.0, min(1.0, pos)) * (len(ramp) - 1)
    i = int(pos)
    f = pos - i
    if i >= len(ramp) - 1:
        return ramp[-1]
    return lerp(ramp[i], ramp[i + 1], f)


def smooth(t):
    t = max(0.0, min(1.0, t))
    return t * t * (3.0 - 2.0 * t)


def glare_disc(ramp, n=256, ring=None):
    """Radial multi-colour disc: bright horizon band at the core, saturated
    middle stops mid, dark zenith at the rim.  `ring` adds a hot-pink horizon
    accent annulus for the late decks."""
    px = []
    for y in range(n):
        for x in range(n):
            dx = (x + 0.5) / n * 2.0 - 1.0
            dy = (y + 0.5) / n * 2.0 - 1.0
            t = min(1.0, (dx * dx + dy * dy) ** 0.5)
            # centre (t=0) reads the bright horizon band; rim the dark zenith
            gpos = 0.70 + (0.06 - 0.70) * smooth(t)
            col = sample_ramp(ramp, gpos)
            # small hot core so the glare has a bright heart, not a flat disc
            if t < 0.22:
                col = lerp(col, (255, 255, 255), (0.22 - t) * 0.55)
            if ring is not None:
                # gaussian accent at t ~ 0.60 using the horizon stop colour
                d = (t - 0.60) / 0.17
                w = 2.718281828 ** (-d * d)
                col = lerp(col, ring, w * 0.42)
            a = (1.0 - t) ** 1.7
            a = smooth(a)
            px.append((int(col[0]), int(col[1]), int(col[2]), int(round(255 * a))))
    return px


def icy_gradient(n=1024):
    """Repaired phase-4 sky strip: deep ice-blue zenith -> pale blue horizon."""
    top = (6, 24, 78)
    mid = (24, 96, 190)
    low = (132, 190, 250)
    px = []
    for y in range(n):
        t = y / (n - 1)
        if t < 0.55:
            col = lerp(top, mid, smooth(t / 0.55))
        else:
            col = lerp(mid, low, smooth((t - 0.55) / 0.45))
        row = []
        for x in range(n):
            row.append((int(col[0]), int(col[1]), int(col[2]), 255))
        px.extend(row)
    return px


JAVA_HEAD = """package net.mcsm.extras.client;

/**
 * AUTO-GENERATED by ci/make_glare_from_sky.py — DO NOT EDIT BY HAND.
 *
 * 16-stop zenith->horizon ramps extracted from the OG sky gradient strips in
 * assets/dabywitherstormmod/textures/mcsm_atmosphere/sky/*.png, plus the glare
 * core/ring accents.  The runtime sky dome and storm glare sample these so
 * the rendered atmosphere is the extracted palette itself.
 */
public final class McsmGlarePalettes {
    public static final int STOPS = %d;

    private McsmGlarePalettes() {
    }
"""


def java_ramp(name, ramp):
    rows = []
    for r, g, b in ramp:
        rows.append("            {%1.3fF, %1.3fF, %1.3fF}," % (r / 255.0, g / 255.0, b / 255.0))
    return ("    /** %s */\n    public static final float[][] %s = {\n%s\n    };\n"
            % (name, name, "\n".join(rows)))


def main():
    check_only = "--check" in sys.argv
    sky = {}
    for key, fname in [("DAY", "day.png"), ("NIGHT", "night.png"),
                       ("SUNSET", "sunset.png"), ("P5_TEAL", "phase5_teal.png"),
                       ("P5_PURPLE", "phase5_purple.png"), ("P55", "phase55.png"),
                       ("P54", "phase54.png"), ("P6", "phase6.png"),
                       ("P1", "phase1.png")]:
        sky[key] = ramp_from(os.path.join(SRC, "mcsm_atmosphere/sky", fname))

    if check_only:
        for key, ramp in sky.items():
            print(key, ["#%02x%02x%02x" % c for c in (ramp[0], ramp[8], ramp[15])])
        return 0

    # ---- repaired phase-4 gradient (src + override) -----------------------
    icy = icy_gradient()
    for base in (SRC, OVR):
        write_png(os.path.join(base, "mcsm_atmosphere/sky/phase4.png"), 1024, 1024, icy)
    sky["P4"] = ramp_from(os.path.join(SRC, "mcsm_atmosphere/sky/phase4.png"))

    # ---- glare discs from the extracted ramps -----------------------------
    glare = {
        "phase4.png": glare_disc(sky["P4"], ring=(120, 190, 255)),
        "phase5.png": glare_disc(sky["P5_TEAL"]),
        "phase54.png": glare_disc(sky["P5_PURPLE"], ring=(200, 90, 200)),
        "phase55.png": glare_disc(sky["P55"], ring=(255, 120, 170)),
        "phase6.png": glare_disc(sky["P6"], ring=(255, 130, 150)),
    }
    for fname, px in glare.items():
        for base in (SRC, OVR):
            write_png(os.path.join(base, "mcsm_atmosphere/glare", fname), 256, 256, px)

    # ---- Java palette header ----------------------------------------------
    out = [JAVA_HEAD % STOPS]
    for key in ["DAY", "NIGHT", "SUNSET", "P1", "P4", "P5_TEAL", "P5_PURPLE",
                "P54", "P55", "P6"]:
        out.append(java_ramp(key, sky[key]))
    out.append("}\n")
    jp = "mcsm-extras/java/net/mcsm/extras/client/McsmGlarePalettes.java"
    with open(jp, "w") as f:
        f.write("".join(out))

    print("[glare] wrote %d glare discs, phase4 gradient + McsmGlarePalettes.java" % len(glare))
    return 0


if __name__ == "__main__":
    sys.exit(main())
